version: 0.1.0.{build}
branches:
  only:
    - master

environment:
  CLI_VERSION: latest
  CLI_ARCH: x64
  DOTNETCLI_ZIP_URL: https://go.microsoft.com/fwlink/?LinkID=831469

install:
  # https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script
  - powershell -NoProfile -ExecutionPolicy unrestricted -Command "&([scriptblock]::Create((Invoke-WebRequest -useb 'https://dot.net/v1/dotnet-install.ps1'))) -Version 2.0.2"
  - dotnet --info

# need build_script, or appveyor starts looking for a sln file
build_script:
  - dotnet restore Entity
  - dotnet restore Roslyn
  - dotnet restore Reflect
  - dotnet publish -r win10-x64 -f netcoreapp2.0 Reflect\Reflect.csproj -o "%APPVEYOR_BUILD_FOLDER%\build"
  - "%APPVEYOR_BUILD_FOLDER%\build\Reflect"